#include "GPIO.h"

/*	PIN CONFIGURATION
		(PB5) MOSI
		(PB3) SCK
		(PB4) DC
		(PA12)CS
		(PA15)RST
*/

void GPIO_Init(void){
	// Enable Ports A&B
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;
	
	// General Output (DC) & Alternate Function (MOSI/SCK)
	GPIOA->MODER &= ~(GPIO_MODER_MODE12 | GPIO_MODER_MODE15);
	GPIOA->MODER |= (GPIO_MODER_MODE12_0 | GPIO_MODER_MODE15_0);
	GPIOB->MODER &= ~(GPIO_MODER_MODE3 | GPIO_MODER_MODE4 | GPIO_MODER_MODE5);
	GPIOB->MODER |= (GPIO_MODER_MODE3_1 | GPIO_MODER_MODE4_0 | GPIO_MODER_MODE5_1);	
	
	// Alternate Function AF5
	GPIOB->AFR[0] &= ~(GPIO_AFRL_AFSEL3 | GPIO_AFRL_AFSEL5); 
	GPIOB->AFR[0] |= (GPIO_AFRL_AFSEL3_2 | GPIO_AFRL_AFSEL3_0 | GPIO_AFRL_AFSEL5_2 | GPIO_AFRL_AFSEL5_0);
	
	// Pull Up
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPD12 | GPIO_PUPDR_PUPD15);
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD3 | GPIO_PUPDR_PUPD4 | GPIO_PUPDR_PUPD5);
	GPIOB->PUPDR |= (GPIO_PUPDR_PUPD3_0 | GPIO_PUPDR_PUPD5_0);
	
	// Output Type: Push-Pull
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT12 | GPIO_OTYPER_OT15);
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT3 | GPIO_OTYPER_OT4 | GPIO_OTYPER_OT5);
	
	// High Output Speed
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR3 | GPIO_OSPEEDER_OSPEEDR4 | GPIO_OSPEEDER_OSPEEDR5);
	GPIOB->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR3 | GPIO_OSPEEDER_OSPEEDR4 | GPIO_OSPEEDER_OSPEEDR5);
	
	// Ignore Output Data Register
	GPIOA->ODR |= GPIO_ODR_ODR_12;
	GPIOB->ODR |= GPIO_ODR_ODR_3;
	GPIOB->ODR |= GPIO_ODR_ODR_4;
	GPIOA->ODR &= ~GPIO_ODR_ODR_15;
	for (int i=0;i<200000;i++); // Some Delay
	GPIOA->ODR |= GPIO_ODR_ODR_15;
	for (int i=0;i<200000;i++); // Some Delay
	
	RCC->AHB2ENR |= RCC_AHB2ENR_RNGEN;
	RNG->CR |=RNG_CR_RNGEN;
	
}

void SPI_Init(void){
	// Disable Spi
	SPI1->CR1 &= ~SPI_CR1_SPE;
	
	// Eanble Spi Clock
	RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
	
	// Spi Reset
	RCC->APB2RSTR |= RCC_APB2RSTR_SPI1RST;
	RCC->APB2RSTR &= ~RCC_APB2RSTR_SPI1RST;
	
	// Spi Polarity & Phase
	SPI1->CR1 &= ~SPI_CR1_CPOL;
	SPI1->CR1 &= ~SPI_CR1_CPHA;
	
	// Master Mode
	SPI1->CR1 |= SPI_CR1_MSTR;
	
	// Enable Software SSM
	SPI1->CR1 |= SPI_CR1_SSM;
	
	// Enable Software CS
	SPI1->CR1 |= SPI_CR1_SSI;
	
	// MSB Orientation
//	SPI1->CR1 &= ~SPI_CR1_LSBFIRST;
	
	// 8-BIT Data
//	SPI1->CR2 &= ~SPI_CR2_DS;
//	SPI1->CR2 |= (SPI_CR2_DS_0 | SPI_CR2_DS_1 | SPI_CR2_DS_2);
	
	// Baud Rate Prescalar = 16 
//	SPI1->CR1 &= ~SPI_CR1_BR;
//	SPI1->CR1 |= (SPI_CR1_BR_0 | SPI_CR1_BR_1);
	
	// Spi Enable
	SPI1->CR1 |= SPI_CR1_SPE;
}


